### ISSUE TITLE
Values containing special characters *and* single quotes are improperly quoted in output

### ISSUE THREAD

**Issue by dabigc** [starkandwayne/safe#201] opened 2020-01-09 19:32 UTC
When running `safe get` on a secret containing special characters and a key-value pair where the value contains a single quote, the value is split at the single quote and re-wrapped with a second single quote. I know I'm not properly describing this. Hopefully, the example below is clearer.

Example key: admin_password
Example value: qTePe_x^'GJm=[3nN*!JfTK_4kk.9Q

Output with `vault read` on the secret containing this key-value pair
```
Key                                     Value
---                                     -----
admin_password              qTePe_x^'GJm=[3nN*!JfTK_4kk.9Q
```

Output with `safe get` on the same secret
```
--- # prod/terraform
admin_password: 'qTePe_x^''GJm=[3nN*!JfTK_4kk.9Q'
```

The value seems to be rendered as two strings together each wrapped with single quotes. My assumption is that the single quote between the ^ and the G in the value is what's causing the issue with the way the value is rendered. Please let me know if I can help in resolving this issue.

**Comment by jhunt** [comment] 2020-01-09 19:38
Interestingly, `spruce merge` seems to be able to read it:

```
→  cat x.yml
--- # prod/terraform
admin_password: 'qTePe_x^''GJm=[3nN*!JfTK_4kk.9Q'

→  spruce merge x.yml
admin_password: qTePe_x^'GJm=[3nN*!JfTK_4kk.9Q
```

**Comment by thomasmitchell** [comment] 2020-01-09 22:06
within single quotes in YAML, a single quote is encoded as `''`, not `\'` as you may expect. This is valid YAML encoding, which is what `safe` outputs when reading out an entire secret. The `vault` CLI does not encode outputs as YAML. Curious to know - if you did `safe get prod/terraform:admin_password`, does it do away with the YAML quoting style?

**Comment by dabigc** [comment] 2020-01-09 22:20
@thomasmitchell Yep, just tested and confirmed that `safe get prod/terraform:admin_password` outputs the value without the YAML quoting style.

**Comment by thomasmitchell** [comment] 2020-02-04 19:33
Closing this, as it's working as intended by outputting as valid YAML.

**Closed by thomasmitchell** 2020-02-04 19:33 UTC
